docs/pages/docs/introduction.es-ES.mdx
=> feat(docs): add translate introduction to `Spanish`

docs/components/home.jsx, docs/globals.css, docs/i18n/translate.js, docs/package.json
=> feat(docs): add translate to presentation

docs/pages/docs/_meta.es-ES.json, docs/pages/docs/accordion.es-ES.mdx, pnpm-lock.yaml
=> feat(docs): translates component accordion to spanish

.prettierignore, docs/components/preview.jsx, docs/lib/cn.ts, docs/package.json, docs/pages/docs/accordion.en-US.mdx, docs/pages/docs/accordion.es-ES.mdx, docs/pages/docs/alert.en-US.mdx, docs/pages/docs/alert.es-ES.mdx, docs/pages/docs/avatar.es-ES.mdx, pnpm-lock.yaml
=> docs: add component Alert

package.json, packages/components/react/package.json, packages/theme/src/create-plugin.ts, packages/theme/src/styles/animations/index.ts, packages/theme/src/styles/index.ts, packages/theme/src/tailwind.ts, pnpm-lock.yaml
=> feat(theme): add animations to styles

packages/components/react/alert/alert-description.tsx, packages/components/react/alert/alert-title.tsx, packages/components/react/alert/alert.tsx, packages/theme/src/components/alert.ts
=> feat: update alert components with variant props

packages/components/react/avatar/avatar.tsx, packages/theme/src/components/avatar.ts
=> feat: add styles to Avatar comp

package.json, packages/components/react/dialog/dialog-content.tsx, packages/theme/src/components/dialog.ts, packages/theme/src/interfaces/utils.d.ts, packages/theme/src/styles/animations/index.ts, packages/theme/src/styles/colors/index.ts
=> feat: add styles of the dialog component

packages/components/react/select/select-trigger.tsx, packages/theme/src/components/select.ts
=> fix(theme): fixed text color for component `Select`

playground/app/page.tsx, src/components/layouts/card/card.tsx, src/plugins/components/card.ts
=> feat: styles for the card component

src/components/elements/badge/badge.tsx, src/plugins/components/badge.ts
=> feat: style for the badge component

src/components/forms/input/input.tsx, src/plugins/components/input.ts
=> feat: style for the Input component

docs/.gitignore, docs/README.md, docs/app/api/search/route.ts, docs/app/docs/[[...slug]]/page.tsx, docs/app/docs/layout.tsx, docs/app/global.css, docs/app/layout.config.tsx, docs/app/layout.tsx, docs/app/page.tsx, docs/app/source.ts, docs/content/docs/index.mdx, docs/content/docs/test.mdx, docs/mdx-components.tsx, docs/next.config.mjs, docs/package.json, docs/postcss.config.js, docs/tailwind.config.js, docs/tsconfig.json, eslint.config.mjs, package.json, pnpm-lock.yaml, pnpm-workspace.yaml, src/components/layouts/card/card.tsx, src/plugins/components/card.ts
=> docs: upgrade fumadocs to 13.2.2

src/components/elements/dropdown/dropdown-content.tsx, src/plugins/components/dropdown.ts
=> feat: styles for dropdown component

src/components/elements/progress/progress-indicator.tsx, src/components/elements/progress/progress.tsx, src/plugins/components/progress.ts
=> feat: style for progress component

src/components/forms/select/select-trigger.tsx, src/plugins/components/select.ts
=> feat: style for select component

src/components/navigations/tabs/tabs-trigger.tsx, src/plugins/components/tabs.ts
=> feat: style for tabs component

src/components/overlays/tooltip/tooltip-tigger.tsx, src/plugins/components/tooltip.ts
=> feat: style for tooltip component

docs/content/docs/figma.mdx, docs/content/docs/frameworks/astro.mdx, docs/content/docs/frameworks/nextjs.mdx, docs/content/docs/frameworks/remix.mdx, docs/content/docs/frameworks/vite.mdx, docs/content/docs/installation.mdx, docs/content/docs/meta.json, docs/mdx-components.tsx
=> docs: improve guide installation

docs/content/docs/components/slider.mdx, docs/mdx-components.tsx
=> docs: component slider

docs/content/docs/components/skeleton.mdx, docs/mdx-components.tsx
=> docs: component skeleton
